# Generated by Django 5.1.7 on 2025-05-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_acessorios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acessorios',
            new_name='Acessorio',
        ),
    ]
