# Generated by Django 5.1.7 on 2025-05-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'ordering': ['nome'], 'verbose_name': 'Cor', 'verbose_name_plural': 'Cor'},
        ),
    ]
